service: api-card

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20200924

iam:
  role:
    statements:
      - Effect: Allow
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:GetItem"
          - "dynamodb:DeleteItem"
          - "dynamodb:Scan"
        Resource:
          - { "Fn::GetAtt": ["CardsTable", "Arn"] }

functions:
  createCard:
    handler: src/handlers.createCard
    events:
      - httpApi:
          path: /card
          method: post
  getCard:
    handler: src/handlers.getCard
    events:
      - httpApi:
          path: /card/{id}
          method: get
  updateCard:
    handler: src/handlers.updateCard
    events:
      - httpApi:
          path: /card/{id}
          method: put
  deleteCard:
    handler: src/handlers.deleteCard
    events:
      - httpApi:
          path: /card/{id}
          method: delete
  listCard:
    handler: src/handlers.listCard
    events:
      - httpApi:
          path: /cards
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline

resources:
  Resources:
    CardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CardsTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: cardID
            AttributeType: S
        KeySchema:
          - AttributeName: cardID
            KeyType: HASH
