service: api-card

frameworkVersion: "2"

package:
  individually: true
  exclude:
    - node_modules/**
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20200924

iam:
  role:
    statements:
      - Effect: Allow
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:GetItem"
          - "dynamodb:DeleteItem"
          - "dynamodb:Scan"
        Resource:
          - { "Fn::GetAtt": ["CardsTable", "Arn"] }

functions:
  createCard:
    handler: src/controller/CardController.createCard
    events:
      - httpApi:
          path: /card
          method: post
  getCard:
    handler: src/controller/CardController.getCard
    events:
      - httpApi:
          path: /card/{id}
          method: get
  getCards:
    handler: src/controller/CardController.getCards
    events:
      - httpApi:
          path: /cards
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-reducer

resources:
  Resources:
    CardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CardsTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: cardID
            AttributeType: S
        KeySchema:
          - AttributeName: cardID
            KeyType: HASH
